build:
  version: "2.0"

accounts:
  message: "Welcome to accounts related QA APIs "

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qa_accountsdb
    username: qa_user
    password: qa_pass

 
